services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env.docker
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 4000:4000
    command: mix phx.server
    env_file:
      - .env.docker
    depends_on:
      - db